---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{APP_NAME}}-configmap-{{ENV_NAME}}
  namespace: {{ENV_NAME}}
data:
  nginx.conf: |
    worker_processes 1;

    events { worker_connections 1024; }

    http {
        server_tokens off;

        server {
            root /usr/share/nginx/html/;
            index index.html;
            server_name localhost;
            listen 80;
        }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{APP_NAME}}
  namespace: {{ENV_NAME}}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{APP_NAME}}
  template:
    metadata:
      labels:
        app: {{APP_NAME}}
    spec:
      containers:
      - name: {{APP_NAME}}
        image: {{GCP_CONTAINER_REGISTRY_HOSTNAME}}/{{PROJECT_ID}}/{{TARGET_BUILD_IMAGE_NAME}}:{{TARGET_BUILD_IMAGE_VERSION}}
        ports:
        - containerPort: 80
        volumeMounts:
        - name: {{APP_NAME}}-volume
          mountPath: /etc/nginx
          readOnly: true
        - name: {{APP_NAME}}-log-volume
          mountPath: /var/log/nginx
        resources:  # must specify requests for CPU to autoscale
          requests:
            cpu: "250m"
            memory: "100Mi"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 1
          failureThreshold: 3
      volumes:
      - name: {{APP_NAME}}-volume
        configMap:
          name: {{APP_NAME}}-configmap-{{ENV_NAME}}
          items:
            - key: nginx.conf
              path: nginx.conf
      - name: {{APP_NAME}}-log-volume
        emptyDir: {}

---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{APP_NAME}}
  namespace: {{ENV_NAME}}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{APP_NAME}}
  minReplicas: {{APP_MIN_REPLICAS}}
  maxReplicas: {{APP_MAX_REPLICAS}}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
  - type: Resource
    resource:
      name: memory
      target:
        type: AverageValue
        averageValue: 100Mi

---
apiVersion: v1
kind: Service
metadata:
  name: {{APP_NAME}}
  namespace: {{ENV_NAME}}
spec:
  selector: 
    app: {{APP_NAME}}
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
